#!/bin/bash

# Make results

for X in Runs/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  do
  RUN_DIR="$X"
  if [ ! -e "$RUN_DIR/Results" ] ; then
      echo "No results directory: $RUN_DIR/Results"
      continue
  fi
  
  echo "Process $RUN_DIR/Results"
  runResults "$RUN_DIR/Results"
  mv *html "$RUN_DIR/"

  # This is the important file (for me)
  cp "$RUN_DIR/bsbm_query_and_size_tables_of_stores.html" "$RUN_DIR/bsbm-query-results.html"

  # The load figures.
  if [ -e "$RUN_DIR/load.log" ]
      then
      genLoadResults < "$RUN_DIR/load.log" > "$RUN_DIR/bsbm-load-results.txt"
  fi

done
