#!/bin/bash

. ./init

DIRS="50k 250k 1m 5m 25m 100m 200m"

for d in $DIRS
do

  SET="$DATADIR/data-$d"
  DB="$JENADB/DB-$d"
  LOC="$DB/Store"

  if [ ! -e "$LOC" ]
      then
      echo "== No such directory: $LOC" 1>&2
      continue 
  fi

  if [ -e "$LOC/stats.opt" ]
  then
      echo "== Stats ($d)"
      tdbstats --loc "$LOC" > stats.opt
      mv stats.opt "$LOC"
  fi

  echo "== Assembler ($d)"
  sed -e "s/SIZE/$d/" assembler-template.ttl > "$SET/assembler.ttl"
done
