#!/bin/bash

. ./init

[ -d "$JENADB" ] || { echo "Not a directory: $JENADB" ; exit 1 ; }

##DIRS="50k 250k 1m 5m 25m 100m 200m"
DIRS="${SIZES:-50k 250k 1m 5m 25m 100m 200m}"
DIRS=50k

##rm -rf Results/*

## ---- Setup
## Need to add -Xmx1024M for 32 bit
#PROFILE="-agentpath:c:/Progra~1/YourKi~1.13/bin/win32/yjpagent.dll"
JVM_ARGS="-Xmx1024M -server $PROFILE"

# TestDriver args
# -seed 808080
# Need more runs
ARGS="-runs 10 -w 10"

# TDB logging.
## **** RunBSBM.java has  
## ????TDB_ARGS="-Dtdb:logExec=true" 

PROGRAM=benchmark.testdriver.TestDriver
PROGRAM=benchmark.testdriver.TestDriver
## ----

rm -rf Results
mkdir Results
JVM_ARGS="-Xmx1400M -server"

for d in $DIRS
do
  SET="$DATADIR/data-$d"
  DB="$JENADB/DB-$d"

  if [ ! -e "$DB/Store" ]
      then
      echo "No database for "
      continue
      fi
  echo "==== Performance run for $d"
  echo "== Start: $(date +"%Y-%m-%d %H:%M:%S")"
  java -cp "$CLASSPATH" $JVM_ARGS \
       $PROGRAM \
       $ARGS -idir "$SET" -o "Results/res-$d.xml" \
      "jena:$DB/assembler.ttl"
  echo "== Finish: $(date +"%Y-%m-%d %H:%M:%S")"
  done
