#!/bin/bash

. ./init

[ -d "$JENADB" ] || { echo "Not a directory: $JENADB" ; exit 1 ; }

DIRS="${SIZES:-50k 250k 1m 5m 25m 100m 200m}"

# TestDriver args
# -seed 808080
# Need more runs
ARGS="-runs 10 -w 5"
#ARGS="-runs 1 -w 0 -ucf  usecases/businessIntelligence/sparql.txt"

# TDB logging.
## ????TDB_ARGS="-Dtdb:logExec=true" 

PROGRAM=benchmark.testdriver.TestDriver
## ----

genKey() {
    local K="$1" 
    local i=1
    while [ -e "$K-$i.html" ]
    do
	i=$((i+1))
    done
    echo "$K-$i.html"
}

## rm -rf Results
## mkdir Results
JVM_ARGS="-Xmx1400M -server"

rm -f Results/*.xml

for d in $DIRS
do
  SET="$DATADIR/data-$d"
  DB="$JENADB/DB-$d"

  if [ ! -e "$DB/Store" ]
      then
      echo "No database for $DB/Store"
      continue
      fi
  echo "==== Performance run for $d"
  echo "== Start: $(date +"%Y-%m-%d %H:%M:%S")"
  java -cp "$CLASSPATH" $JVM_ARGS \
      $PROGRAM \
      $ARGS -idir "$SET" -o "Results/res-$d.xml" \
      "jena:$DB/assembler.ttl"
      #"http://localhost:3030/ds/sparql"
  echo "== Finish: $(date +"%Y-%m-%d %H:%M:%S")"
  done

F=$(genKey "Reports/results")
runResults Results/res*xml > $F
