#!/bin/bash

. ./init

[ -d "$JENADB" ] || { echo "Not a directory: $JENADB" ; exit 1 ; }

DIRS="${SIZES:-50k 250k 1m 5m 25m 100m 200m}"

# TestDriver args
# -seed 808080
# Need more runs
ARGS="-runs 25 -w 25"

# TDB logging.
## ????TDB_ARGS="-Dtdb:logExec=true" 

PROGRAM=benchmark.testdriver.TestDriver
## ----

## rm -rf Results
## mkdir Results
JVM_ARGS="-Xmx1400M -server"

for d in $DIRS
do
  SET="$DATADIR/data-$d"
  DB="$JENADB/DB-$d"

  if [ ! -e "$DB/Store" ]
      then
      echo "No database for $DB/Store"
      continue
      fi
  echo "==== Performance run for $d"
  echo "== Start: $(date +"%Y-%m-%d %H:%M:%S")"
  java -cp "$CLASSPATH" $JVM_ARGS \
      $PROGRAM \
      $ARGS -idir "$SET" -o "Results/res-$d.xml" \
      "jena:$DB/assembler.ttl"
      #"http://localhost:3030/ds/sparql"
  echo "== Finish: $(date +"%Y-%m-%d %H:%M:%S")"
  done

runResults Results/res*xml > Results/results-$(date date '+%Y-%m-%dT%H:%M:%S').html
