#!/bin/bash
# Take a copy of scripts

## ssh local name
HOST=dev1

# Run ivy to get remote jar files setup

rsync -av --delete src build.xml $HOST:Projects/BSBM-Jena
ssh $HOST "cd Projects/BSBM-Jena ; ant clean compile"
